name: Update README cards

on:
  schedule:
    - cron: "0 0 * * *" # runs daily at midnight UTC
  workflow_dispatch:     # lets you trigger it manually too

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v6

      - name: Generate stats card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: stats
          options: "username=traejiik&show_icons=true&include_all_commits=true&count_private=true&bg_color=00000000&border_color=FFFFFF&title_color=58A6FF&text_color=C9D1D9&icon_color=58A6FF"
          path: output/stats.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate top languages card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: top-langs
          options: "username=traejiik&layout=compact&langs_count=10&bg_color=0000000&border_color=FFFFFF&title_color=58A6FF&text_color=C9D1D9"
          path: output/top-langs.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate weather-app pin card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: pin
          options: "username=traejiik&repo=weather-app&bg_color=00000000&border_color=FFFFFF&title_color=58A6FF&text_color=C9D1D9&icon_color=58A6FF"
          path: output/pin-weather-app.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate cv-application pin card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: pin
          options: "username=traejiik&repo=cv-application&bg_color=00000000&border_color=FFFFFF&title_color=58A6FF&text_color=C9D1D9&icon_color=58A6FF"
          path: output/pin-cv-application.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit cards
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add output/*.svg
          git commit -m "chore: update README cards" || exit 0
          git push
